name: rx-nostr test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rx-nostr-test
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: node index.js
